version: '2.0'
services:
  code-server:
    build: .
    ports:
      - "8080:8080"
    hostname: code
    environment: 
      - USERNAME=${USER}
      - PUID=${UID}
      - PGID=${GID}
    volumes: 
      - $HOME:/home/${USER}
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - redis
  redis:
    image: "redis:5.0.8"
