version: '2.0'
services:
  code-server:
    build: .
    ports:
      - "8080-8090:8080-8090"
    hostname: code
    environment: 
      - USERNAME=${USER}
      - PUID=${UID}
      - PGID=${GID}
    volumes: 
      - $HOME:/home/${USER}
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - redis
      - spanner
  redis:
    image: "redis:5.0.8"
  spanner:
    image: "gcr.io/cloud-spanner-emulator/emulator"